#!/usr/bin/perl
use strict;
use warnings;
my $src = shift @ARGV;
my $dst = shift @ARGV;
die "Cannot find source directory $src" unless defined($src) and -d $src;
die "Cannot find destination directory $dst" unless defined($dst) and -d $dst;
mkdir "$dst/empty";
mkdir "$dst/good";
mkdir "$dst/mixed";
my %C;
my @L = glob "$src/*/*.png";
# For detail image size of 96 with 18 overlap - 1 less than number of images
my $lidx = 9;
## For detail image size of 96 with 8 overlap - 1 less than number of images
#my $lidx = 8;
## For detail image size of 64 - 1 less than number of images
#my $lidx = 11;
for my $file (@L) {
  my ($name) = $file =~ /([^\/]+)\.png$/;
  my ($tag) = $file =~ /_([^_.\/]+)\.png$/;
  next unless defined $tag;
  next if $tag eq "g" or  $tag eq "m";
  print STDERR "Processing $name\n";
  # This is for 96 with 18 overlap
  system "convert $file -set filename:0 \"%[t]\" \\( +clone -roll +78+0 +clone -roll +78+0 +clone -roll +78+0 +clone -roll +78+0 +clone -roll +78+0 +clone -roll +78+0 +clone -roll +78+0 +clone -roll +78+0 +clone -roll +98+0 \\) -extent 96x96 \"%[filename:0]_%d.png\"";
  ## This is for 96 with 8 overlap
  #system "convert $file -set filename:0 \"%[t]\" \\( +clone -roll +88+0 +clone -roll +88+0 +clone -roll +88+0 +clone -roll +88+0 +clone -roll +88+0 +clone -roll +88+0 +clone -roll +88+0 +clone -roll +96+0 \\) -extent 96x96 \"%[filename:0]_%d.png\"";
  ## This is for 64, skipping first 16 rows of pixels
  #system "convert $file -set filename:0 \"%[t]\" -roll +0+80 \\( +clone -roll +64+0 +clone -roll +64+0 +clone -roll +64+0 +clone -roll +64+0 +clone -roll +64+0 +clone -roll +64+0 +clone -roll +64+0 +clone -roll +64+0 +clone -roll +64+0 +clone -roll +64+0 +clone -roll +96+0 \\) -extent 64x64 \"%[filename:0]_%d.png\"";
  my @D;
  if ($tag eq "e") {
    push @D, ("empty") x ($lidx + 1);
  } else {
    my $v = hex $tag;
    for my $i (0 .. $lidx) {
      my $dn = $v & 3;
      my $ds = "unk";
      $ds = "empty" if $dn == 1;
      $ds = "good" if $dn == 2;
      $ds = "mixed" if $dn == 3;
      unshift @D, $ds;
      $v >>= 2;
    }
  }
  for my $i (0 .. $lidx) {
    $C{$D[$i]} += 1;
    if ($D[$i] eq "unk") {
      unlink "${name}_$i.png";
    } else {
      system "mv ${name}_$i.png $dst/$D[$i]";
    }
  }
}
for my $class (sort keys %C) {
  printf STDERR "%s\t%u\n", $class, $C{$class};
}
exit 0;
__END__
../../../Downloads/IMAGES_231210/03
img0300_16a95.png
img0301_16a55.png
img0336_e.png
img0337_15595.png

convert img0500.png -set filename:0 "%[t]" \( +clone -roll +88+0 +clone -roll +88+0 +clone -roll +88+0 +clone -roll +88+0 +clone -roll +88+0 +clone -roll +88+0 +clone -roll +88+0 +clone -roll +96+0 \) -extent 96x96 "%[filename:0]_%d.png"
