// ImageFileInfo.idl
namespace ImageSorter
{
  enum ImageClassValue {
      Unclassified = 0,
      Empty = 1,
      Good = 2,
      Mixed = 3
  };

    [Microsoft.UI.Xaml.Data.Bindable]
    runtimeclass ImageFileInfo : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ImageFileInfo(Windows.Storage.StorageFile File);
        String Path{ get; };
        String Name{ get; };
        Int32 Class{ get; set; };
        String ClassColor{ get; };
        Int32 ClassFromDetails{ get; };
        Int32 RectIdx{ get; set; };
        Int32 RectLeft{ get; };
        Microsoft.UI.Xaml.Window DetailWindow{ get; set; };
        Int32 getDetail(UInt32 idx);
        void setDetail(UInt32 idx, Int32 value);
        void NextRect();
        Windows.Foundation.IAsyncAction rename(String desiredName);
        event Microsoft.UI.Xaml.Data.PropertyChangedEventHandler PropertyChanged;
    }

    runtimeclass ImagesRepository
    {
        ImagesRepository();
        Windows.Foundation.Collections.IObservableVector<ImageSorter.ImageFileInfo> Images{ get; };
        Windows.Foundation.IAsyncAction GetImages(String folderPath, Microsoft.UI.Dispatching.DispatcherQueue queue);
    }
//        public ImageInfo(string fullName, string name)
//        public string Name { get; set; };
//        public string FullName { get; set; };
//        public int ImageClass { get; set; };
//        public string ImageClassColor { get; };
//        public int ClassFromDetail { get; };
//        public int RectIdx { get; set; };
//        public void NextRect ();
//        public int RectLeft { get; };
//        public event PropertyChangedEventHandler PropertyChanged;
//        protected virtual void OnPropertyChanged(string propertyName);
//        private int rectIdx = 0;
//        public static SolidColorBrush[] ColorBrush = {
//            new SolidColorBrush(Colors.Gold),
//            new SolidColorBrush(Colors.White),
//            new SolidColorBrush(Colors.SpringGreen),
//            new SolidColorBrush(Colors.Red),
//            new SolidColorBrush(Colors.Blue),
//        };
//        private Window detailWindow = null;
//        public Window DetailWindow { get; set; };
//        public uint[] detail;
//        private string fullName;
//        public const uint NbDetailImg = 9;

//    runtimeclass ImagesRepository : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
//    {
//        public ObservableCollection<ImageInfo> Images;
//        public void GetImages(string folderPath);
//    }
}
