// ImageFileInfo.idl
namespace ImageSorter
{
  enum ImageClassValue {
      Unclassified = 0,
      Empty = 1,
      Good = 2,
      Mixed = 3
  };

    runtimeclass ImageFileInfo : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ImageFileInfo(Windows.Storage.FileProperties.ImageProperties properties, Windows.Storage.StorageFile imageFile, String name, String type, Microsoft.UI.Dispatching.DispatcherQueue queue);
        Windows.Storage.FileProperties.ImageProperties ImageProperties{ get; };
        Windows.Storage.StorageFile ImageFile{ get; };
        String ImageName{ get; };
        String ImageFileType{ get; };
        String ImageDimensions{ get; };
        String ImageTitle;
        Int32 ImageClass;
        Microsoft.UI.Dispatching.DispatcherQueue UIQueue{ get; };
    }
}