// ImageFileInfo.idl
namespace ImageSorter
{
    [Microsoft.UI.Xaml.Data.Bindable]
    runtimeclass ImageFileInfo : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ImageFileInfo(Windows.Storage.StorageFile File);
        String Path{ get; };
        String Name{ get; };
        Int32 Class{ get; set; };
        String ClassColor{ get; };
        Int32 ClassFromDetails{ get; };
        Int32 RectIdx{ get; set; };
        Int32 RectLeft{ get; };
        Microsoft.UI.Xaml.Window DetailWindow{ get; set; };
        Int32 getDetail(UInt32 idx);
        void setDetail(UInt32 idx, Int32 value);
        void NextRect();
        Windows.Foundation.IAsyncAction rename(String desiredName);
        event Microsoft.UI.Xaml.Data.PropertyChangedEventHandler PropertyChanged;
    }

    runtimeclass ImagesRepository
    {
        ImagesRepository();
        Windows.Foundation.Collections.IObservableVector<ImageSorter.ImageFileInfo> Images{ get; };
        Windows.Foundation.IAsyncAction GetImages(String folderPath, Microsoft.UI.Dispatching.DispatcherQueue queue);
    }
}
